### ISSUE TITLE
Permission Denied when running the container

### ISSUE THREAD

**Issue by arowland-informatics** [kerbe/docker-expo#2]
Running this container give the following error:

EACCES: permission denied, mkdir '/app/.expo'

This makes the container inaccessible, so there is no way to exec in and investigate

Error Stack:

EACCES: permission denied, mkdir '/app/.expo'

Error: EACCES: permission denied, mkdir '/app/.expo'

at Object.mkdirSync (fs.js:956:3)

at Object.module.exports.makeDirSync (/usr/local/lib/node_modules/expo-cli/node_modules/fs-extra/lib/mkdirs/make-dir.js:102:15)

at dotExpoProjectDirectory (/@expo/xdl@58.0.14/src/ProjectSettings.ts:133:6)

at projectSettingsJsonFile (/@expo/xdl@58.0.14/src/ProjectSettings.ts:41:15)

at Object.setAsync (/@expo/xdl@58.0.14/src/ProjectSettings.ts:91:18)

at cacheOptionsAsync (/usr/local/lib/node_modules/expo-cli/src/commands/start.ts:115:25)

at normalizeOptionsAsync (/usr/local/lib/node_modules/expo-cli/src/commands/start.ts:110:9)

at /usr/local/lib/node_modules/expo-cli/src/commands/start.ts:329:41

at /usr/local/lib/node_modules/expo-cli/src/exp.ts:660:12

at Command.<anonymous> (/usr/local/lib/node_modules/expo-cli/src/exp.ts:332:13)

**Comment by kerbe** [comment]
Hello @arowland-informatics, my deepest apologies for not noticing this issue earler!
Have you got this problem solved?
Have you attached volume to container? You could bypass default entrypoint with this:
`sudo docker run -it --entrypoint /bin/bash [docker_image]`
And it drops you into bash prompt, and you could try investigate what is happening.

**Comment by kerbe** [comment]
Closing this issue, as there hasn't been any reply. If problem still persist, don't hesitate to comment here & ping me.
